/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Secure;

import java.sql.*;

/**
 *
 * @author Demon
 */
public class SecondPass extends javax.swing.JFrame {

    /**
     * Creates new form SecondPass
     */
    public SecondPass() {
        initComponents();
    }
public String useraaya;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSbtBtn2 = new javax.swing.JButton();
        jSecondPass = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Enter Secured PIN");

        jSbtBtn2.setText("Submit");
        jSbtBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSbtBtn2ActionPerformed(evt);
            }
        });

        jSecondPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSecondPassActionPerformed(evt);
            }
        });

        jLabel3.setText("             ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSbtBtn2)
                .addGap(166, 166, 166))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSecondPass)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addComponent(jLabel3)))
                .addContainerGap(152, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jSecondPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(jSbtBtn2)
                .addGap(28, 28, 28)
                .addComponent(jLabel3)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    void changekar(String a)
    {
    useraaya=a;
    }
    
    private void jSecondPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSecondPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jSecondPassActionPerformed
    int getUser()
    {
        return Integer.parseInt(useraaya);
    }
    private void jSbtBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSbtBtn2ActionPerformed
        // TODO add your handling code here:
        Login lg=new Login();
       // int juser=lg.getUserId();
        
        //System.out.println(useraaya);
        Connection conn;
        try {
            conn = DriverManager.getConnection("jdbc:derby://localhost:1527/UserLogin","qwerty","12345");
            Statement st=conn.createStatement();
            int jus=Integer.parseInt(useraaya);
            ResultSet rs = st.executeQuery("select Password2 from Usertable where UserId="+jus+"");
           int pass1=0;
           while(rs.next())
            {   
                pass1=rs.getInt(1);  
            }
            String pass2 =Integer.toString(pass1);
            String jpass=jSecondPass.getText();
            if(jpass.equals(pass2))
            {
                ThirdPass tp=new ThirdPass();
                tp.third(useraaya);
                tp.setVisible(true);
                this.setVisible(false);
            }
            else
                jLabel3.setText("Wrong password");
            }
        catch (SQLException ex) 
            {
            jLabel3.setText("Connection Lost");
            }
    }//GEN-LAST:event_jSbtBtn2ActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SecondPass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SecondPass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SecondPass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SecondPass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SecondPass().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton jSbtBtn2;
    private javax.swing.JPasswordField jSecondPass;
    // End of variables declaration//GEN-END:variables
}
